# Generated by Django 5.0.6 on 2026-05-13 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_template', models.BooleanField(default=False, help_text='Если True — сборка отображается в публичном каталоге.', verbose_name='Готовая сборка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликована')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Сборка ПК',
                'verbose_name_plural': 'Сборки ПК',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BuildItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='builds.build', verbose_name='Сборка')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='build_items', to='catalog.component', verbose_name='Комплектующее')),
            ],
            options={
                'verbose_name': 'Позиция сборки',
                'verbose_name_plural': 'Позиции сборок',
            },
        ),
        migrations.AddField(
            model_name='build',
            name='components',
            field=models.ManyToManyField(related_name='builds', through='builds.BuildItem', to='catalog.component', verbose_name='Комплектующие'),
        ),
        migrations.AddConstraint(
            model_name='builditem',
            constraint=models.UniqueConstraint(fields=('build', 'component'), name='unique_component_per_build'),
        ),
    ]
